# Generated by Django 4.2.10 on 2024-08-18 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
