# Generated by Django 4.2.10 on 2024-08-20 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
    ]
